django:
  image: omnium/testapp:latest
  command: python manage.py supervisor
  environment:
    RUN_ENV: "$RUN_ENV"
    DATABASE_HOST: "postgresql"
    BROKER_URL: "amqp://guest:guest@rabbitmq//"
  ports:
   - "80:8001"
  volumes:
   - .:/project
  links:
   - redis
   - postgres
   - rabbitmq
   - memcached

celery_worker:
  image: omnium/testapp:latest
  environment:
    C_FORCE_ROOT: "true"
    DATABASE_HOST: "postgresql"
    BROKER_URL: "amqp://guest:guest@rabbitmq//"
  command: python manage.py celery worker -l info
  links:
   - postgres
   - redis
   - rabbitmq

postgres:
  image: postgres:9.1
  volumes:
    - local_postgres:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
    POSTGRESQL_DB: "$POSTGRESQL_DB"
    POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    POSTGRES_USER: "$POSTGRES_USER"  

redis:
  image: redis:latest
  command: redis-server --appendonly yes

rabbitmq:
  image: jcalazan/rabbitmq
  ports:
    - "15672:15672"

memcached:
  image: memcached
  ports:
    - "11211:11211"
